### ISSUE TITLE
UI broken in Patch 0.217.4 – Hildir's Request (public test)

### ISSUE THREAD

**Issue by Quentin-ctrL** [SpikeHimself/XPortal#56]
**Describe the bug**
When editing portal UI, impossible to interact with label or list.
Impossible to close UI. You need to exit session

**To Reproduce**
Patch 0.217.4 – Hildir's Request (public test)
edit portal

**Expected behaviour**
edit portal.

**LogOutput file(s)**

**Version**
Which version of XPortal are you experiencing your problem with?
 XPortal v1.2.11

**Environment**
* Singleplayer (linux)

**Other mods**
none

**Priority**
* High (XPortal does not work at all anymore)

**Additional information**
![](https://user-images.githubusercontent.com/70467477/246576679-50e117ea-3ad6-45de-bbca-0829d3edfaec.png)

see https://github.com/SpikeHimself/XPortal/issues/49#issuecomment-1595557981

**Comment by Quentin-ctrL** [comment]
For information
Patch 0.217.6 (Public Test) 
changelog:  https://store.steampowered.com/news/app/892970/view/3658659836549833064

Does someone confirm the issue is fixed with this patch ?

If not, I will test Xportal with the latest patch when I will have time.

**Comment by noisexoma** [comment]
Valheim 0.217.7 confirm the issue!
![Снимок экрана 2023-06-28 223321](https://github.com/SpikeHimself/XPortal/assets/5262136/cba08909-15c5-4aeb-8537-1252cfc2d5d0)

**Comment by missbanjo** [comment]
Can confirm the issue!  Any chance on an update @SpikeHimself  ?

**Comment by SpikeHimself** [comment]
Hi, thanks for testing! I've been on holiday and will look into this asap. But on first sight (wild guess) it looks like it might be a Jotunn issue, since that's where I get the UI elements from. I will test later and get back on that.

**Comment by JohnnyPDX** [comment]
Still experiencing the issue on 0.217.7. I don't get the pink background, but same interaction issues. I too agree it's probably Jotunn. I'm having a lot of issues with Jotunn dependent mods besides this one.

**Comment by sfjuocekr** [comment]
Still broken yes, doesn't show the missing texture (pink image) but doesn't allow any text input.

**Comment by amazingornaldo** [comment]
Still broken. I even updated to the latest Jotunn from Nexus Mods just to eliminate that as an issue for me.

**Comment by SpikeHimself** [comment]
I released v1.2.14 a few days ago which fixes this issue. Forgot to update her. My apologies.
